name: Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: stable or canary?
        required: true
        type: choice
        options:
          - canary
          - stable

      semverType:
        description: semver type?
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - run: |

          cd ./elwood && rsync -abviuzP ./ ../
          ls

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build Packages
        run: pnpm build

      - name: Install Desktop App
        run: pnpm -C apps/desktop install

      - name: Install Desktop App
        run: pnpm -C apps/desktop build

      - name: Package Desktop App
        run: pnpm -C apps/desktop package

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm -C apps/desktop electron-builder -- --publish always --win
