name: Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: stable or canary?
        required: true
        type: choice
        options:
          - canary
          - stable

      semverType:
        description: semver type?
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Install
        uses: ./.github/composite-actions/install
        with:
          working-directory: ./elwood

      - name: Update submodules
        run: make update

      - name: Build
        run: make build

      - name: Build App
        run: make build-app

      - name: PostInstall Desktop App
        run: |
          cd apps/desktop && \
            ./node_modules/.bin/ts-node .erb/scripts/check-native-dep.js && \
            ./node_modules/.bin/electron-builder install-app-deps  && \
            pnpm run build:dll

      - name: Package Desktop App
        run: cd apps/desktop && pnpm run package

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd apps/desktop && ./node_modules/.bin/electron-builder -- --publish always --win
