name: Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: stable or canary?
        required: true
        type: choice
        options:
          - canary
          - stable

      semverType:
        description: semver type?
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - run: |
          rsync -a ./elwood .
          ls

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build Packages
        run: pnpm build

      - name: Install & Build Desktop App
        run: |
          pnpm i --ignore-scripts
          ./node_modules/.bin/ts-node .erb/scripts/check-native-dep.js
          ./node_modules/.bin/electron-builder install-app-deps
          pnpm run build:dll
          pnpm build

      - name: Package Desktop App
        run: pnpm package

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm electron-builder -- --publish always --win
